In [3]:
#Imort libraries
import pandas as pd
import numpy as np
import yfinance as yf
from datetime import datetime
import matplotlib.pyplot as plt

In [4]:
iShares_World = pd.read_csv("Data//iShares MCSI World Index Data.csv", index_col=0, parse_dates=True, dayfirst=True)
iShares_SNP500 = pd.read_csv("Data//iShares SNP500 Index Data.csv", index_col=0, parse_dates=True, dayfirst=True)
Vanguard_Global_Bond = pd.read_csv("Data//Vanguard Global Bond Data.csv",index_col=0, parse_dates=True, dayfirst=True)
BoE_Rate = pd.read_csv("Data//BoE Interest Rate Data.csv", index_col=0, parse_dates=True, dayfirst=True)

C:\Users\allan\AppData\Local\Temp\ipykernel_20728\3056266843.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  iShares_World = pd.read_csv("Data//iShares MCSI World Index Data.csv", index_col=0, parse_dates=True, dayfirst=True)
C:\Users\allan\AppData\Local\Temp\ipykernel_20728\3056266843.py:2: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  iShares_SNP500 = pd.read_csv("Data//iShares SNP500 Index Data.csv", index_col=0, parse_dates=True, dayfirst=True)
C:\Users\allan\AppData\Local\Temp\ipykernel_20728\3056266843.py:3: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  Vanguard_Global_Bond = pd.read_csv("Data//Vanguard Global Bond Data.csv",index_col=0, parse_dates=True, dayfirst=True)
C:\Users\allan\AppData\Local\Temp\ipykernel_20728\3056266843.py:4: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  BoE_Rate = pd.read_csv("Data//BoE Interest Rate Data.csv", index_col=0, parse_dates=True, dayfirst=True)

In [5]:
iShares_World = iShares_World.rename(columns={"Close": "iShares_World_Close"})
iShares_SNP500 = iShares_SNP500.rename(columns={"Close": "iShares_SNP500_Close"})
Vanguard_Global_Bond = Vanguard_Global_Bond.rename(columns={"Close": "Vanguard_Global_Bond_Close"})
BoE_Rate = BoE_Rate.rename(columns={"Rate": "BoE_Rate"})

In [6]:
iShares_World = iShares_World["iShares_World_Close"]
iShares_SNP500 = iShares_SNP500["iShares_SNP500_Close"]
Vanguard_Global_Bond = Vanguard_Global_Bond[ "Vanguard_Global_Bond_Close"]

In [7]:
merged = pd.merge(iShares_World,iShares_SNP500,on="Date")
merged = pd.merge(merged,Vanguard_Global_Bond,on="Date")
merged = pd.merge(merged,BoE_Rate,on="Date")

merged

,iShares_World_Close,iShares_SNP500_Close,Vanguard_Global_Bond_Close,BoE_Rate
Date,,,,
2025-07-01,"10,878.00","14,371.00",155.31,4.25
2025-06-01,"10,719.00","14,130.00",156.29,4.25
2025-05-01,"10,335.00","13,442.00",154.85,4.50
2025-04-01,"9,681.50","12,577.00",155.39,4.50
2025-03-01,"9,727.00","12,648.00",153.97,4.50
...,...,...,...,...
2014-05-01,"3,866.50","4,371.50",133.24,0.50
2014-04-01,"3,775.00","4,265.50",131.96,0.50
2014-03-01,"3,751.50","4,243.00",131.05,0.50
2014-02-01,"3,756.00","4,227.50",130.88,0.50
2014-01-01,"3,600.00","4,047.50",130.23,0.50

In [8]:
merged = merged.replace(',','', regex=True)
merged

,iShares_World_Close,iShares_SNP500_Close,Vanguard_Global_Bond_Close,BoE_Rate
Date,,,,
2025-07-01,10878.00,14371.00,155.31,4.25
2025-06-01,10719.00,14130.00,156.29,4.25
2025-05-01,10335.00,13442.00,154.85,4.50
2025-04-01,9681.50,12577.00,155.39,4.50
2025-03-01,9727.00,12648.00,153.97,4.50
...,...,...,...,...
2014-05-01,3866.50,4371.50,133.24,0.50
2014-04-01,3775.00,4265.50,131.96,0.50
2014-03-01,3751.50,4243.00,131.05,0.50
2014-02-01,3756.00,4227.50,130.88,0.50
2014-01-01,3600.00,4047.50,130.23,0.50

In [9]:
merged.dtypes

iShares_World_Close            object
iShares_SNP500_Close           object
Vanguard_Global_Bond_Close    float64
BoE_Rate                      float64
dtype: object

In [10]:
merged[["iShares_World_Close", "iShares_SNP500_Close"]]=merged[["iShares_World_Close", "iShares_SNP500_Close"]].astype(float)
merged.dtypes

iShares_World_Close           float64
iShares_SNP500_Close          float64
Vanguard_Global_Bond_Close    float64
BoE_Rate                      float64
dtype: object

In [11]:
date_range = pd.date_range('2015-01-01', '2024-12-31', freq='MS')
year_starts = pd.date_range('2015-01-01', '2024-12-31', freq='YS')

In [12]:
print(year_starts)

DatetimeIndex(['2015-01-01', '2016-01-01', '2017-01-01', '2018-01-01',
               '2019-01-01', '2020-01-01', '2021-01-01', '2022-01-01',
               '2023-01-01', '2024-01-01'],
              dtype='datetime64[ns]', freq='AS-JAN')

In [13]:
def regular(iShares_World_prop,iShares_SNP500_prop,Vanguard_Global_Bond_prop,Cash_prop):

    #PROPORTIONS
    # iShares_World_prop = 0.3
    # iShares_SNP500_prop = 0.3
    # Vanguard_Global_Bond_prop = 0.3
    #Cash_prop = 0.1

    total_shares = 0
    total_invested = 0
    
    iShares_World_total_shares = 0
    iShares_SNP500_total_shares = 0
    Vanguard_Global_Bond_total_shares = 0
    Cash_total = 0
    
    df = pd.DataFrame({'Date': [], 'iShares_World_Value': [], 'iShares_SNP500_Value': [],
                       "Vanguard_Global_Bond_Value":[],"Cash_total":[], "Total_Value":[]}).set_index("Date")
    
    
    for date in date_range:
        #iShares World
        iShares_World_current_close = merged.loc[date,"iShares_World_Close"]
        iShares_World_total_shares =  iShares_World_total_shares + (100*iShares_World_prop/iShares_World_current_close)
        iShares_World_Value = iShares_World_total_shares*iShares_World_current_close
        
        #iShares SNP500
        iShares_SNP500_current_close = merged.loc[date,"iShares_SNP500_Close"]
        iShares_SNP500_total_shares =  iShares_SNP500_total_shares + (100*iShares_SNP500_prop/iShares_SNP500_current_close)
        iShares_SNP500_Value = iShares_SNP500_total_shares * iShares_SNP500_current_close
        
        #iShares SNP500
        Vanguard_Global_Bond_current_close = merged.loc[date,"Vanguard_Global_Bond_Close"]
        Vanguard_Global_Bond_total_shares =  Vanguard_Global_Bond_total_shares + (100*Vanguard_Global_Bond_prop/Vanguard_Global_Bond_current_close)
        Vanguard_Global_Bond_Value = Vanguard_Global_Bond_total_shares*Vanguard_Global_Bond_current_close
        
        #Cash
        BoE_current_rate = merged.loc[date,"BoE_Rate"]
        BoE_current_rate_monthly = BoE_current_rate/12
        Cash_total = (100*Cash_prop) + (BoE_current_rate_monthly*Cash_total/100) + Cash_total
        Total_Value=(iShares_World_total_shares*iShares_World_current_close + 
                     iShares_SNP500_total_shares*iShares_SNP500_current_close + 
                     Vanguard_Global_Bond_total_shares*Vanguard_Global_Bond_current_close + Cash_total)
    
        newrow = pd.DataFrame({'Date': [date], 'iShares_World_Value': [iShares_World_Value], 'iShares_SNP500_Value': [iShares_SNP500_Value],
        "Vanguard_Global_Bond_Value":[Vanguard_Global_Bond_Value],"Cash_total":[Cash_total], "Total_Value": [Total_Value]}).set_index("Date")
    
        df = pd.concat([df, newrow])
   
    
    results = df
    return results

In [14]:
def rebalancing_yearly(iShares_World_prop,iShares_SNP500_prop,Vanguard_Global_Bond_prop,Cash_prop):

    total_shares = 0
    total_invested = 0
    
    iShares_World_total_shares = 0
    iShares_SNP500_total_shares = 0
    Vanguard_Global_Bond_total_shares = 0
    Cash_total = 0
    Total_Value = 0
    
    df = pd.DataFrame({'Date': [], 'iShares_World_Value': [], 'iShares_SNP500_Value': [],
                       "Vanguard_Global_Bond_Value":[],"Cash_total":[], "Total_Value":[]}).set_index("Date")
    
    
    for date in date_range:
        if date in year_starts:
            #iShares World
            iShares_World_current_close = merged.loc[date,"iShares_World_Close"]
            iShares_World_total_shares =  (Total_Value+100)*iShares_World_prop/iShares_World_current_close
            iShares_World_Value = iShares_World_total_shares*iShares_World_current_close
            
            #iShares SNP500
            iShares_SNP500_current_close = merged.loc[date,"iShares_SNP500_Close"]
            iShares_SNP500_total_shares =  (Total_Value + 100)*iShares_SNP500_prop/iShares_SNP500_current_close
            iShares_SNP500_Value = iShares_SNP500_total_shares * iShares_SNP500_current_close
            
            #iShares SNP500
            Vanguard_Global_Bond_current_close = merged.loc[date,"Vanguard_Global_Bond_Close"]
            Vanguard_Global_Bond_total_shares = (Total_Value + 100)*Vanguard_Global_Bond_prop/Vanguard_Global_Bond_current_close
            Vanguard_Global_Bond_Value = Vanguard_Global_Bond_total_shares*Vanguard_Global_Bond_current_close
            
            #Cash
            BoE_current_rate = merged.loc[date,"BoE_Rate"]
            BoE_current_rate_monthly = BoE_current_rate/12
            Cash_total = (100+Total_Value)*Cash_prop

        else:
            #iShares World
            iShares_World_current_close = merged.loc[date,"iShares_World_Close"]
            iShares_World_total_shares =  iShares_World_total_shares + (100*iShares_World_prop/iShares_World_current_close)
            iShares_World_Value = iShares_World_total_shares*iShares_World_current_close
            
            #iShares SNP500
            iShares_SNP500_current_close = merged.loc[date,"iShares_SNP500_Close"]
            iShares_SNP500_total_shares =  iShares_SNP500_total_shares + (100*iShares_SNP500_prop/iShares_SNP500_current_close)
            iShares_SNP500_Value = iShares_SNP500_total_shares * iShares_SNP500_current_close
            
            #iShares SNP500
            Vanguard_Global_Bond_current_close = merged.loc[date,"Vanguard_Global_Bond_Close"]
            Vanguard_Global_Bond_total_shares =  Vanguard_Global_Bond_total_shares + (100*Vanguard_Global_Bond_prop/Vanguard_Global_Bond_current_close)
            Vanguard_Global_Bond_Value = Vanguard_Global_Bond_total_shares*Vanguard_Global_Bond_current_close
            
            #Cash
            BoE_current_rate = merged.loc[date,"BoE_Rate"]
            BoE_current_rate_monthly = BoE_current_rate/12
            Cash_total = (100*Cash_prop) + (BoE_current_rate_monthly*Cash_total/100) + Cash_total
        
        Total_Value=(iShares_World_total_shares*iShares_World_current_close + 
                         iShares_SNP500_total_shares*iShares_SNP500_current_close + 
                         Vanguard_Global_Bond_total_shares*Vanguard_Global_Bond_current_close + Cash_total)
        newrow = pd.DataFrame({'Date': [date], 'iShares_World_Value': [iShares_World_Value], 'iShares_SNP500_Value': [iShares_SNP500_Value],
            "Vanguard_Global_Bond_Value":[Vanguard_Global_Bond_Value],"Cash_total":[Cash_total], "Total_Value": [Total_Value]}).set_index("Date")        
        df = pd.concat([df, newrow])
   
    results = df
    return results

In [15]:
rebalancing_yearly(0.3,0.3,0.3,0.1).loc[year_starts]

,iShares_World_Value,iShares_SNP500_Value,Vanguard_Global_Bond_Value,Cash_total,Total_Value
2015-01-01,30.000000,30.000000,30.000000,10.000000,100.000000
2016-01-01,389.660234,389.660234,389.660234,129.886745,1298.867448
2017-01-01,806.870469,806.870469,806.870469,268.956823,2689.568231
2018-01-01,1276.766180,1276.766180,1276.766180,425.588727,4255.887266
2019-01-01,1534.652367,1534.652367,1534.652367,511.550789,5115.507890
2020-01-01,2101.234103,2101.234103,2101.234103,700.411368,7004.113678
2021-01-01,2678.986061,2678.986061,2678.986061,892.995354,8929.953536
2022-01-01,3468.997249,3468.997249,3468.997249,1156.332416,11563.324162
2023-01-01,3406.162870,3406.162870,3406.162870,1135.387623,11353.876234
2024-01-01,4183.290091,4183.290091,4183.290091,1394.430030,13944.300302

In [16]:
print(regular(0.7,0,0.2,0.1).iloc[-1][-1])

18520.81806061636

In [17]:
print(rebalancing_yearly(0.7,0,0.2,0.1).iloc[-1][-1])

17379.940849405404

In [18]:
def invest_yearly(iShares_World_prop,iShares_SNP500_prop,Vanguard_Global_Bond_prop,Cash_prop):

    total_shares = 0
    total_invested = 0
    
    iShares_World_total_shares = 0
    iShares_SNP500_total_shares = 0
    Vanguard_Global_Bond_total_shares = 0
    Cash_total = 0
    Total_Value = 0
    
    df = pd.DataFrame({'Date': [], 'iShares_World_Value': [], 'iShares_SNP500_Value': [],
                       "Vanguard_Global_Bond_Value":[],"Cash_total":[], "Total_Value":[]}).set_index("Date")
    
    
    for date in date_range:
        if date in year_starts:
            #iShares World
            iShares_World_current_close = merged.loc[date,"iShares_World_Close"]
            iShares_World_total_shares =  iShares_World_total_shares + (1000*iShares_World_prop/iShares_World_current_close)
            iShares_World_Value = iShares_World_total_shares*iShares_World_current_close
            
            #iShares SNP500
            iShares_SNP500_current_close = merged.loc[date,"iShares_SNP500_Close"]
            iShares_SNP500_total_shares =  iShares_SNP500_total_shares + (1000*iShares_SNP500_prop/iShares_SNP500_current_close)
            iShares_SNP500_Value = iShares_SNP500_total_shares * iShares_SNP500_current_close
            
            #iShares SNP500
            Vanguard_Global_Bond_current_close = merged.loc[date,"Vanguard_Global_Bond_Close"]
            Vanguard_Global_Bond_total_shares =  Vanguard_Global_Bond_total_shares + (1000*Vanguard_Global_Bond_prop/Vanguard_Global_Bond_current_close)
            Vanguard_Global_Bond_Value = Vanguard_Global_Bond_total_shares*Vanguard_Global_Bond_current_close
            
            #Cash
            BoE_current_rate = merged.loc[date,"BoE_Rate"]
            BoE_current_rate_monthly = BoE_current_rate/12
            Cash_total = (1000*Cash_prop) + (BoE_current_rate_monthly*Cash_total/100) + Cash_total
        else:
            #iShares World
            iShares_World_current_close = merged.loc[date,"iShares_World_Close"]
            iShares_World_Value = iShares_World_total_shares*iShares_World_current_close
            
            #iShares SNP500
            iShares_SNP500_current_close = merged.loc[date,"iShares_SNP500_Close"]
            iShares_SNP500_Value = iShares_SNP500_total_shares * iShares_SNP500_current_close
            
            #iShares SNP500
            Vanguard_Global_Bond_current_close = merged.loc[date,"Vanguard_Global_Bond_Close"]
            Vanguard_Global_Bond_Value = Vanguard_Global_Bond_total_shares*Vanguard_Global_Bond_current_close
            
            #Cash
            BoE_current_rate = merged.loc[date,"BoE_Rate"]
            BoE_current_rate_monthly = BoE_current_rate/12
            Cash_total = (BoE_current_rate_monthly*Cash_total/100) + Cash_total            
        
        Total_Value=(iShares_World_total_shares*iShares_World_current_close + 
                         iShares_SNP500_total_shares*iShares_SNP500_current_close + 
                         Vanguard_Global_Bond_total_shares*Vanguard_Global_Bond_current_close + Cash_total)
        newrow = pd.DataFrame({'Date': [date], 'iShares_World_Value': [iShares_World_Value], 'iShares_SNP500_Value': [iShares_SNP500_Value],
                                "Vanguard_Global_Bond_Value":[Vanguard_Global_Bond_Value],"Cash_total":[Cash_total], 
                               "Total_Value": [Total_Value]}).set_index("Date")        
        df = pd.concat([df, newrow])
   
    results = df
    return results

In [19]:
print(regular(0.7,0,0.2,0.1).iloc[-1][-1])
print(invest_yearly(0.7,0,0.2,0.1).iloc[-1][-1])

18520.81806061636
15931.854553397776

In [20]:
print(invest_yearly(0.7,0,0.2,0.1).tail(20))

            iShares_World_Value  iShares_SNP500_Value  \
Date
2023-05-01          8716.944293                   0.0
2023-06-01          9222.257246                   0.0
2023-07-01          9492.073062                   0.0
2023-08-01          9351.248140                   0.0
2023-09-01          9018.711981                   0.0
2023-10-01          8717.535994                   0.0
2023-11-01          9410.418275                   0.0
2023-12-01          9854.194288                   0.0
2024-01-01         10766.023371                   0.0
2024-02-01         11177.375075                   0.0
2024-03-01         11574.804107                   0.0
2024-04-01         11266.606753                   0.0
2024-05-01         11546.958760                   0.0
2024-06-01         12008.938367                   0.0
2024-07-01         12086.145917                   0.0
2024-08-01         12232.966833                   0.0
2024-09-01         12429.149954                   0.0
2024-10-01         12393.710422                   0.0
2024-11-01         12973.399901                   0.0
2024-12-01         12786.076663                   0.0

            Vanguard_Global_Bond_Value   Cash_total   Total_Value
Date
2023-05-01                 1723.019175   935.426965  11375.390433
2023-06-01                 1718.699929   938.934816  11879.891991
2023-07-01                 1718.699929   942.847045  12153.620035
2023-08-01                 1714.020746   946.775574  12012.044460
2023-09-01                 1678.506946   950.917717  11648.136645
2023-10-01                 1665.069293   955.077982  11337.683269
2023-11-01                 1725.178798   959.256449  12094.853522
2023-12-01                 1783.008701   963.453195  12600.656185
2024-01-01                 1977.729623  1067.668303  13811.421297
2024-02-01                 1958.775880  1072.339352  14208.490308
2024-03-01                 1976.261375  1077.030837  14628.096319
2024-04-01                 1939.421706  1081.742847  14287.771306
2024-05-01                 1957.040678  1086.475472  14590.474910
2024-06-01                 1972.257063  1091.228802  15072.424232
2024-07-01                 2012.700613  1096.002928  15194.849458
2024-08-01                 2033.923466  1100.569607  15367.459906
2024-09-01                 2058.349768  1105.155313  15592.655035
2024-10-01                 2024.580072  1109.760127  15528.050621
2024-11-01                 2051.275484  1114.384128  16139.059512
2024-12-01                 2026.982659  1118.795231  15931.854553

SyntaxError: invalid syntax (1311334025.py, line 4)