In [81]:
#Imort libraries
import pandas as pd
import numpy as np
import yfinance as yf
from datetime import datetime
import matplotlib.pyplot as plt

In [82]:
iShares_World = pd.read_csv("Data//iShares MCSI World Index Data.csv", index_col=0, parse_dates=True, dayfirst=True)
iShares_SNP500 = pd.read_csv("Data//iShares SNP500 Index Data.csv", index_col=0, parse_dates=True, dayfirst=True)
Vanguard_Global_Bond = pd.read_csv("Data//Vanguard Global Bond Data.csv",index_col=0, parse_dates=True, dayfirst=True)
BoE_Rate = pd.read_csv("Data//BoE Interest Rate Data.csv", index_col=0, parse_dates=True, dayfirst=True)

C:\Users\allan\AppData\Local\Temp\ipykernel_16964\3056266843.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  iShares_World = pd.read_csv("Data//iShares MCSI World Index Data.csv", index_col=0, parse_dates=True, dayfirst=True)
C:\Users\allan\AppData\Local\Temp\ipykernel_16964\3056266843.py:2: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  iShares_SNP500 = pd.read_csv("Data//iShares SNP500 Index Data.csv", index_col=0, parse_dates=True, dayfirst=True)
C:\Users\allan\AppData\Local\Temp\ipykernel_16964\3056266843.py:3: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  Vanguard_Global_Bond = pd.read_csv("Data//Vanguard Global Bond Data.csv",index_col=0, parse_dates=True, dayfirst=True)
C:\Users\allan\AppData\Local\Temp\ipykernel_16964\3056266843.py:4: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  BoE_Rate = pd.read_csv("Data//BoE Interest Rate Data.csv", index_col=0, parse_dates=True, dayfirst=True)

In [83]:
iShares_World = iShares_World.rename(columns={"Close": "iShares_World_Close"})
iShares_SNP500 = iShares_SNP500.rename(columns={"Close": "iShares_SNP500_Close"})
Vanguard_Global_Bond = Vanguard_Global_Bond.rename(columns={"Close": "Vanguard_Global_Bond_Close"})
BoE_Rate = BoE_Rate.rename(columns={"Rate": "BoE_Rate"})

In [84]:
iShares_World = iShares_World["iShares_World_Close"]
iShares_SNP500 = iShares_SNP500["iShares_SNP500_Close"]
Vanguard_Global_Bond = Vanguard_Global_Bond[ "Vanguard_Global_Bond_Close"]

In [85]:
merged = pd.merge(iShares_World,iShares_SNP500,on="Date")
merged = pd.merge(merged,Vanguard_Global_Bond,on="Date")
merged = pd.merge(merged,BoE_Rate,on="Date")

merged

,iShares_World_Close,iShares_SNP500_Close,Vanguard_Global_Bond_Close,BoE_Rate
Date,,,,
2025-07-01,"10,878.00","14,371.00",155.31,4.25
2025-06-01,"10,719.00","14,130.00",156.29,4.25
2025-05-01,"10,335.00","13,442.00",154.85,4.50
2025-04-01,"9,681.50","12,577.00",155.39,4.50
2025-03-01,"9,727.00","12,648.00",153.97,4.50
...,...,...,...,...
2014-05-01,"3,866.50","4,371.50",133.24,0.50
2014-04-01,"3,775.00","4,265.50",131.96,0.50
2014-03-01,"3,751.50","4,243.00",131.05,0.50
2014-02-01,"3,756.00","4,227.50",130.88,0.50
2014-01-01,"3,600.00","4,047.50",130.23,0.50

In [86]:
merged = merged.replace(',','', regex=True)
merged

,iShares_World_Close,iShares_SNP500_Close,Vanguard_Global_Bond_Close,BoE_Rate
Date,,,,
2025-07-01,10878.00,14371.00,155.31,4.25
2025-06-01,10719.00,14130.00,156.29,4.25
2025-05-01,10335.00,13442.00,154.85,4.50
2025-04-01,9681.50,12577.00,155.39,4.50
2025-03-01,9727.00,12648.00,153.97,4.50
...,...,...,...,...
2014-05-01,3866.50,4371.50,133.24,0.50
2014-04-01,3775.00,4265.50,131.96,0.50
2014-03-01,3751.50,4243.00,131.05,0.50
2014-02-01,3756.00,4227.50,130.88,0.50
2014-01-01,3600.00,4047.50,130.23,0.50

In [87]:
merged.dtypes

iShares_World_Close            object
iShares_SNP500_Close           object
Vanguard_Global_Bond_Close    float64
BoE_Rate                      float64
dtype: object

In [88]:
merged[["iShares_World_Close", "iShares_SNP500_Close"]]=merged[["iShares_World_Close", "iShares_SNP500_Close"]].astype(float)
merged.dtypes

iShares_World_Close           float64
iShares_SNP500_Close          float64
Vanguard_Global_Bond_Close    float64
BoE_Rate                      float64
dtype: object

In [97]:
date_range = pd.date_range('2015-01-01', '2024-12-31', freq='MS')

In [100]:
#PROPORTIONS
iShares_World_prop = 0.3
iShares_SNP500_prop = 0.3
Vanguard_Global_Bond_prop = 0.3
Cash_prop = 0.1

total_shares = 0
total_invested = 0

iShares_World_total_shares = 0
iShares_SNP500_total_shares = 0
Vanguard_Global_Bond_total_shares = 0
Cash_total = 0

df = pd.DataFrame({'Date': [], 'iShares_World_Value': [], 'iShares_SNP500_Value': [],
                   "Vanguard_Global_Bond_Value":[],"Cash_total":[], "Total_Value":[]}).set_index("Date")


for date in date_range:
    #iShares World
    iShares_World_current_close = merged.loc[date,"iShares_World_Close"]
    iShares_World_total_shares =  iShares_World_total_shares + (100*iShares_World_prop/iShares_World_current_close)
    iShares_World_Value = iShares_World_total_shares*iShares_World_current_close
    
    #iShares SNP500
    iShares_SNP500_current_close = merged.loc[date,"iShares_SNP500_Close"]
    iShares_SNP500_total_shares =  iShares_SNP500_total_shares + (100*iShares_SNP500_prop/iShares_SNP500_current_close)
    iShares_SNP500_Value = iShares_SNP500_total_shares * iShares_SNP500_current_close
    
    #iShares SNP500
    Vanguard_Global_Bond_current_close = merged.loc[date,"Vanguard_Global_Bond_Close"]
    Vanguard_Global_Bond_total_shares =  Vanguard_Global_Bond_total_shares + (100*Vanguard_Global_Bond_prop/Vanguard_Global_Bond_current_close)
    Vanguard_Global_Bond_Value = Vanguard_Global_Bond_total_shares*Vanguard_Global_Bond_current_close
    
    #Cash
    BoE_current_rate = merged.loc[date,"BoE_Rate"]
    BoE_current_rate_monthly = BoE_current_rate/12
    Cash_total = (100*Cash_prop) + (BoE_current_rate_monthly*Cash_total/100) + Cash_total
    Total_Value=(iShares_World_total_shares*iShares_World_current_close + 
                 iShares_SNP500_total_shares*iShares_SNP500_current_close + 
                 Vanguard_Global_Bond_total_shares*Vanguard_Global_Bond_current_close + Cash_total)

    newrow = pd.DataFrame({'Date': [date], 'iShares_World_Value': [iShares_World_Value], 'iShares_SNP500_Value': [iShares_SNP500_Value],
    "Vanguard_Global_Bond_Value":[Vanguard_Global_Bond_Value],"Cash_total":[Cash_total], "Total_Value": [Total_Value]}).set_index("Date")

    df = pd.concat([df, newrow])
#print(df)
print(df.iloc[-1])

iShares_World_Value            6323.185705
iShares_SNP500_Value           6912.823755
Vanguard_Global_Bond_Value     3648.149750
Cash_total                     1334.618248
Total_Value                   18218.777458
Name: 2024-12-01 00:00:00, dtype: float64